CREATE DATABASE BAITHI
GO

USE BAITHI
GO

--1--
CREATE TABLE NHACUNGCAP (
	MANCC CHAR(5) PRIMARY KEY,
	TENNCC VARCHAR(50),
	QUOCGIA VARCHAR(20),
	LOAINCC VARCHAR(50),
);

CREATE TABLE DUOCPHAM (
	MADP CHAR(5) PRIMARY KEY,
	TENDP VARCHAR(50),
	LOAIDP VARCHAR(20),
	GIA MONEY,
);

CREATE TABLE PHIEUNHAP (
	SOPN CHAR(5) PRIMARY KEY,
	NGNHAP SMALLDATETIME,
	MANCC CHAR(5) FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
	LOAINHAP VARCHAR(30),
);

CREATE TABLE CTPN (
	SOPN CHAR(5) FOREIGN KEY REFERENCES PHIEUNHAP(SOPN),
	MADP CHAR(5) FOREIGN KEY REFERENCES DUOCPHAM(MADP),
	SOLUONG INT,
	PRIMARY KEY (SOPN, MADP),
);

--2--
 SET DATEFORMAT DMY

INSERT INTO dbo.NHACUNGCAP(MANCC, TENNCC, QUOCGIA, LOAINCC) VALUES ('NCC01', 'Phuc Hung', 'Viet Nam', 'Thuong xuyen')
INSERT INTO dbo.NHACUNGCAP(MANCC, TENNCC, QUOCGIA, LOAINCC) VALUES ('NCC02', 'J. B. Pharmaceuticals', 'India', 'Vang lai')
INSERT INTO dbo.NHACUNGCAP(MANCC, TENNCC, QUOCGIA, LOAINCC) VALUES ('NCC03', 'Sapharco ', 'Singapore', 'Vang lai')

INSERT INTO dbo.DUOCPHAM(MADP, TENDP, LOAIDP, GIA) VALUES ('DP01','Thuoc ho PH','Siro', 120000)
INSERT INTO dbo.DUOCPHAM(MADP, TENDP, LOAIDP, GIA) VALUES ('DP02','Zecuf Herbal CouchRemedy','Vien nen', 200000)
INSERT INTO dbo.DUOCPHAM(MADP, TENDP, LOAIDP, GIA) VALUES ('DP03','Cotrim','Vien sui',80000)

INSERT INTO dbo.PHIEUNHAP(SOPN, NGNHAP, MANCC, LOAINHAP) VALUES ('00001', '22/11/2017', 'NCC01', 'Noi dia')
INSERT INTO dbo.PHIEUNHAP(SOPN, NGNHAP, MANCC, LOAINHAP) VALUES ('00002', '04/12/2017', 'NCC03', 'Nhap khau')
INSERT INTO dbo.PHIEUNHAP(SOPN, NGNHAP, MANCC, LOAINHAP) VALUES ('00003', '10/12/2017', 'NCC02', 'Nhap khau')

INSERT INTO dbo.CTPN(SOPN, MADP, SOLUONG) VALUES ('00001', 'DP01', 100)
INSERT INTO dbo.CTPN(SOPN, MADP, SOLUONG) VALUES ('00001', 'DP02', 200)
INSERT INTO dbo.CTPN(SOPN, MADP, SOLUONG) VALUES ('00003', 'DP03', 543)

--3--
ALTER TABLE DUOCPHAM
ADD CONSTRAINT CK_GIA_SIRO 
CHECK (LOAIDP != 'Siro' OR GIA > 100000);

--4--
CREATE TRIGGER TRG_PHIEUNHAP_INS_UPD
ON dbo.PHIEUNHAP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MaNCC CHAR(5), @LoaiNhap varchar(30), @QuocGia varchar(20)

	SELECT @MaNCC = MANCC, @LoaiNhap = LOAINHAP
	FROM inserted

	SELECT @QuocGia = QUOCGIA
	FROM dbo.NHACUNGCAP
	WHERE MANCC = @MaNCC

	IF (@QuocGia = 'Viet Nam' AND @LoaiNhap != 'Noi dia')
	BEGIN
		RAISERROR(N'Phiếu nhập của những nhà cung cấp ở những quốc gia khác Việt Nam đều có loại nhập là Nhập khẩu', 16, 1)
		ROLLBACK TRAN
	END
	ELSE 
	BEGIN
		PRINT 'THANH CONG'
	END
END
GO

CREATE TRIGGER TRG_NHACUNGCAP_UPD 
ON dbo.NHACUNGCAP
FOR UPDATE
AS
BEGIN
	DECLARE @MaNCC CHAR(5), @LoaiNhap varchar(30), @QuocGia varchar(20)

	SELECT @MaNCC = MANCC, @QuocGia = QUOCGIA
	FROM inserted

	SELECT @LoaiNhap = LOAINHAP
	FROM dbo.PHIEUNHAP
	WHERE MANCC = @MaNCC

	IF (@QuocGia = 'Viet Nam' AND @LoaiNhap != 'Noi dia')
	BEGIN
		RAISERROR(N'Phiếu nhập của những nhà cung cấp ở những quốc gia khác Việt Nam đều có loại nhập là Nhập khẩu', 16, 1)
		ROLLBACK TRAN
	END
	ELSE 
	BEGIN
		PRINT 'THANH CONG'
	END
END
GO

--5--
SELECT *
FROM dbo.PHIEUNHAP
WHERE MONTH(NGNHAP) = 12 AND YEAR(NGNHAP) = 2017
ORDER BY DAY(NGNHAP) ASC

--6--
SELECT TOP 1 WITH TIES CT.MADP
FROM dbo.DUOCPHAM AS DP
JOIN dbo.CTPN AS CT ON CT.MADP = DP.MADP
JOIN dbo.PHIEUNHAP AS PN ON PN.SOPN = CT.SOPN
WHERE YEAR(NGNHAP) = 2017
GROUP BY CT.MADP
ORDER BY SUM(SOLUONG) DESC

--7--
SELECT DP.MADP, TENDP
FROM dbo.DUOCPHAM AS DP
JOIN dbo.CTPN AS CT ON CT.MADP = DP.MADP
JOIN dbo.PHIEUNHAP AS PN ON PN.SOPN = CT.SOPN
JOIN dbo.NHACUNGCAP AS NCC ON NCC.MANCC = PN.MANCC
WHERE LOAINCC = 'Thuong xuyen'
AND DP.MADP NOT IN (
	SELECT DP.MADP
	FROM dbo.DUOCPHAM AS DP
	JOIN dbo.CTPN AS CT ON CT.MADP = DP.MADP
	JOIN dbo.PHIEUNHAP AS PN ON PN.SOPN = CT.SOPN
	JOIN dbo.NHACUNGCAP AS NCC ON NCC.MANCC = PN.MANCC
	WHERE LOAINCC = 'Vang lai'
)

--8--
SELECT *
FROM dbo.NHACUNGCAP AS NCC
WHERE NOT EXISTS (
	SELECT *
	FROM dbo.DUOCPHAM AS DP
	WHERE GIA > 100000
	AND NOT EXISTS (
		SELECT *
		FROM dbo.CTPN AS CT 
		JOIN dbo.PHIEUNHAP AS PN ON PN.SOPN = CT.SOPN
		WHERE YEAR(NGNHAP) = 2017
		AND PN.MANCC = NCC.MANCC
		AND CT.MADP = DP.MADP
	)
)