CREATE DATABASE LAZADA1
GO

USE LAZADA1
GO

CREATE TABLE KHACHHANG(
    MAKH CHAR(4) PRIMARY KEY,
    TENKH VARCHAR(50),
    DIACHI VARCHAR(50),
    LOAIKH VARCHAR(40),
);

CREATE TABLE LOAICAY(
    MALC CHAR(4) PRIMARY KEY,
    TENLC VARCHAR(50),
    XUATXU VARCHAR(40),
    GIA MONEY,
);

CREATE TABLE HOADON(
    SOHD INT PRIMARY KEY,
    NGHD SMALLDATETIME,
    MAKH CHAR(4),
    KHUYENMAI INT,
);

CREATE TABLE CTHD(
    SOHD INT FOREIGN KEY REFERENCES HOADON(SOHD),
    MALC CHAR(4) FOREIGN KEY REFERENCES LOAICAY(MALC),
    SOLUONG INT,
    PRIMARY KEY(SOHD, MALC)
);

INSERT INTO KHACHHANG VALUES ('KH01', 'Liz Kim Cuong', 'Ha Noi', 'Vang lai')
INSERT INTO KHACHHANG VALUES ('KH02', 'Ivone Dieu Linh', 'Da Nang', 'Thuong xuyen')
INSERT INTO KHACHHANG VALUES ('KH03', 'Emma Nhat Khanh', 'TP.HCM', 'Vang lai')

INSERT INTO LOAICAY VALUES ('LC01','Xuong rong tai tho','Mexico','180000')
INSERT INTO LOAICAY VALUES ('LC02','Sen thach ngoc','Anh','300000')
INSERT INTO LOAICAY VALUES ('LC03','Ba mau rau','Nam Phi','270000')

SET DATEFORMAT DMY
INSERT INTO HOADON VALUES ('00001','22/11/2017','KH01','5')
INSERT INTO HOADON VALUES ('00002','04/12/2017','KH03','5')
INSERT INTO HOADON VALUES ('00003','10/12/2017','KH02','10')

INSERT INTO CTHD VALUES ('00001','LC01','1')
INSERT INTO CTHD VALUES ('00001','LC02','2')
INSERT INTO CTHD VALUES ('00003','LC03','5')

--3--
ALTER TABLE LOAICAY
ADD CONSTRAINT CHECK_LC CHECK(XUATXU != 'Anh' OR  GIA >250000 )


--5--
SELECT *
FROM HOADON 
WHERE MONTH(NGHD) IN (10,11,12) 
    AND YEAR(NGHD) = 2017
ORDER BY KHUYENMAI ASC 

--6--
SELECT TOP 1 WITH TIES LC.MALC, LC.TENLC
FROM LOAICAY LC 
JOIN CTHD CT ON CT.MALC = LC.MALC
JOIN HOADON HD ON HD.SOHD = CT.SOHD 
WHERE MONTH(HD.NGHD) = 12
GROUP BY LC.MALC, LC.TENLC
ORDER BY SUM(SOLUONG) ASC

--7--.
SELECT LC.MALC, LC.TENLC
FROM LOAICAY LC
JOIN CTHD CT ON CT.MALC = LC.MALC
JOIN HOADON HD ON HD.SOHD = CT.SOHD
JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
WHERE KH.LOAIKH = 'Thuong xuyen'
INTERSECT
SELECT LC.MALC, LC.TENLC
FROM LOAICAY LC
JOIN CTHD CT ON CT.MALC = LC.MALC
JOIN HOADON HD ON HD.SOHD = CT.SOHD
JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
WHERE KH.LOAIKH = 'Vang lai'

--8--
SELECT KH.MAKH, KH.TENKH 
FROM KHACHHANG KH
WHERE NOT EXISTS(
    SELECT *
    FROM LOAICAY LC
    WHERE NOT EXISTS (
        SELECT *
        FROM CTHD CT, HOADON HD 
        WHERE CT.SOHD = HD.SOHD 
        AND CT.MALC = LC.MALC
        AND HD.MAKH = KH.MAKH
    )
)


--4--
GO
CREATE TRIGGER TRG_UPD_KM
ON HOADON
AFTER UPDATE
AS
BEGIN
IF EXISTS (
SELECT *
FROM inserted I
JOIN CTHD CT ON CT.SOHD = I. SOHD
WHERE I. KHUYENMAI <> 10
GROUP BY I. SOHD
HAVING (SUM (CT.SOLUONG) >= 5))
BEGIN
RAISERROR ('LOI CAP NHAT', 16,1)
ROLLBACK TRANSACTION
END
ELSE
PRINT ('THANH CONG')
END;

go
CREATE TRIGGER TRG_CTHD
ON CTHD
AFTER INSERT, UPDATE
AS 
BEGIN
UPDATE HOADON
SET KHUYENMAI = 10
WHERE KHUYENMAI <> 10 AND HOADON. SOHD IN (
SELECT CT.SOHD
FROM CTHD CT
GROUP BY CT.SOHD
HAVING (SUM(CT.SOLUONG) >=5))
PRINT ('DA CAP NHAT')
END