
--1--
SELECT DISTINCT CTHD.SOHD
FROM dbo.HOADON JOIN dbo.CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE MASP IN('BB01', 'BB02')
	AND SL BETWEEN 10 AND 20
	AND TRIGIA > 500000

--2--
SELECT DISTINCT C1.SOHD
FROM dbo.CTHD AS C1
JOIN dbo.CTHD AS C2 ON C1.SOHD = C2.SOHD
JOIN dbo.CTHD AS C3 ON C1.SOHD = C3.SOHD
JOIN dbo.HOADON AS HD ON C1.SOHD = HD.SOHD
WHERE C1.MASP = 'BB01' AND C1.SL BETWEEN 10 AND 20
  AND C2.MASP = 'BB02' AND C2.SL BETWEEN 10 AND 20
  AND C3.MASP = 'BB03' AND C3.SL BETWEEN 10 AND 20
  AND YEAR(HD.NGHD) = 2023;

 --3--
 SELECT KH.MAKH, HOTEN, SUM(TRIGIA) AS TONGTRIGIA
 FROM dbo.KHACHHANG AS KH 
 JOIN dbo.HOADON AS HD ON HD.MAKH = KH.MAKH
 JOIN dbo.CTHD ON CTHD.SOHD = HD.SOHD
 WHERE MASP = 'BB01' 
	AND SL BETWEEN 10 AND 20
 GROUP BY KH.MAKH, HOTEN
 HAVING SUM(TRIGIA) >= 1000000

 --4--
 SELECT NV.MANV, NV.HOTEN
 FROM dbo.CTHD 
 JOIN dbo.HOADON AS HD ON CTHD.SOHD = HD.SOHD
 JOIN dbo.NHANVIEN AS NV ON NV.MANV = HD.MANV
 WHERE MASP IN('BB01', 'BB02') 
	AND SL >= 15
GROUP BY NV.MANV, NV.HOTEN
HAVING SUM(TRIGIA) >= 2000000

--5--
SELECT KH.MAKH, HOTEN
FROM dbo.KHACHHANG AS KH
JOIN dbo.HOADON AS HD ON HD.MAKH = KH.MAKH
JOIN dbo.CTHD ON CTHD.SOHD = HD.SOHD
GROUP BY KH.MAKH, HOTEN
HAVING COUNT(DISTINCT MASP) >= 2
	AND SUM(SL) >= 50
	AND SUM(DISTINCT TRIGIA) >= 5000000

--6--
SELECT DISTINCT KH.MAKH, HOTEN, HD.SOHD
FROM dbo.KHACHHANG AS KH
JOIN dbo.HOADON AS HD ON HD.MAKH = KH.MAKH
JOIN dbo.CTHD ON CTHD.SOHD = HD.SOHD
WHERE HD.SOHD IN (
	SELECT SOHD 
	FROM dbo.CTHD
	WHERE SL > 5
	GROUP BY SOHD
	HAVING COUNT(DISTINCT MASP) >= 3
)

--7--
SELECT SP.MASP, TENSP
FROM dbo.SANPHAM AS SP
JOIN dbo.CTHD AS C ON SP.MASP = C.MASP
JOIN dbo.HOADON AS HD ON HD.SOHD = C.SOHD
WHERE NUOCSX = 'Trung Quoc'
	AND YEAR(NGHD) = 2007
GROUP BY SP.MASP, TENSP
HAVING COUNT(C.MASP) >= 5

--8--
SELECT KH.MAKH, HOTEN
FROM dbo.KHACHHANG AS KH
JOIN dbo.HOADON AS HD ON HD.MAKH = KH.MAKH
JOIN dbo.CTHD AS C ON C.SOHD = HD.SOHD
JOIN dbo.SANPHAM AS SP ON SP.MASP = C.MASP
WHERE NUOCSX = 'Singapore'
	AND YEAR(NGHD) = 2006
GROUP BY KH.MAKH, HOTEN
HAVING SUM(TRIGIA) > 1000000

--9--
WITH NVBH AS (
	SELECT NV.MANV, HOTEN, SUM(C.SL) AS SOLUONG
	FROM dbo.NHANVIEN AS NV
	JOIN dbo.HOADON AS HD ON HD.MANV = NV.MANV
	JOIN dbo.CTHD AS C ON C.SOHD = HD.SOHD
	JOIN dbo.SANPHAM AS SP ON SP.MASP = C.MASP
	WHERE NUOCSX = 'Trung Quoc'
		AND YEAR(NGHD) = 2006
	GROUP BY NV.MANV, HOTEN
)

SELECT MANV, HOTEN
FROM NVBH
WHERE SOLUONG = (
	SELECT MAX(SOLUONG)
	FROM NVBH
)

--10--
SELECT DISTINCT KH.MAKH, KH.HOTEN
FROM dbo.KHACHHANG AS KH
JOIN dbo.HOADON AS HD ON KH.MAKH = HD.MAKH
JOIN dbo.CTHD AS CTHD ON HD.SOHD = CTHD.SOHD
JOIN dbo.SANPHAM AS SP ON CTHD.MASP = SP.MASP
WHERE SP.NUOCSX = 'Trung Quoc'
  AND KH.MAKH NOT IN (
      SELECT KH.MAKH
      FROM dbo.KHACHHANG AS KH
      JOIN dbo.HOADON AS HD ON KH.MAKH = HD.MAKH
      JOIN dbo.CTHD AS CTHD ON HD.SOHD = CTHD.SOHD
      JOIN dbo.SANPHAM AS SP ON CTHD.MASP = SP.MASP
      WHERE SP.NUOCSX = 'Singapore'
 );

 --11--
 SELECT HD.SOHD
 FROM dbo.HOADON AS HD
 WHERE NOT EXISTS (
	SELECT *
	FROM dbo.SANPHAM AS SP
	WHERE NUOCSX = 'Singapore'
	AND NOT EXISTS (
		SELECT *
		FROM dbo.CTHD AS C
		WHERE C.MASP = SP.MASP
			AND HD.SOHD = C.SOHD
	)
 )
 AND HD.TRIGIA > (
	SELECT AVG(TRIGIA)
	FROM dbo.HOADON
 )

--12--
WITH NVBH AS (
	SELECT NV.MANV, HOTEN, SUM(C.SL) AS SOLUONGBANRA
	FROM dbo.NHANVIEN AS NV
	JOIN dbo.HOADON AS HD ON HD.MANV = NV.MANV
	JOIN dbo.CTHD AS C ON C.SOHD = HD.SOHD
	JOIN dbo.SANPHAM AS SP ON SP.MASP = C.MASP
	GROUP BY NV.MANV, HOTEN
)

SELECT *
FROM NVBH
WHERE SOLUONGBANRA > (
	SELECT AVG(SOLUONGBANRA)
	FROM NVBH
)

--13--
WITH NUOCSX_HD AS (
	SELECT SP.NUOCSX, HD.SOHD
	FROM dbo.HOADON AS HD
	JOIN dbo.CTHD AS C ON C.SOHD = HD.SOHD
	JOIN dbo.SANPHAM AS SP ON SP.MASP = C.MASP
)

SELECT DISTINCT HD.SOHD
FROM dbo.HOADON AS HD
WHERE NOT EXISTS (
	SELECT *
	FROM dbo.SANPHAM AS SP
	WHERE NOT EXISTS (
		SELECT *
		FROM NUOCSX_HD AS N
		WHERE N.NUOCSX = SP.NUOCSX
			AND N.SOHD = HD.SOHD
	)
)