--15-- Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này.
CREATE TRIGGER TRG_INS_UPD_HVTHI
ON dbo.KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (
		SELECT *
		FROM inserted AS KQ
		JOIN dbo.GIANGDAY AS GD ON KQ.MAMH = GD.MAMH
		WHERE DENNGAY > NGTHI
	)
		BEGIN 
			PRINT N'Học viên chỉ được thi môn này khi học xong môn học'
			ROLLBACK TRAN
		END
END
GO

--16--
CREATE TRIGGER TRG_INS_UPD_MHMoiKy
ON dbo.GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @SoLuongMH INT, @MaLop CHAR(10), @HocKy INT, @Nam INT, @SoMH_HT INT

	SELECT @SoLuongMH = COUNT(MAMH), @MaLop = MALOP, @HocKy = HOCKY, @Nam = NAM
	FROM inserted
	GROUP BY MALOP, HOCKY, NAM

	SELECT @SoMH_HT = COUNT(MAMH)
	FROM dbo.GIANGDAY
	WHERE MALOP = @MaLop AND HOCKY = @HocKy AND NAM = @Nam
	GROUP BY MALOP, HOCKY, NAM

	IF (@SoLuongMH + @SoMH_HT > 3)
	BEGIN
		PRINT N'Số lượng môn học mỗi kỳ phải nhở hơn 3'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT N'THANH CONG'
	END
END
GO

--17--
CREATE TRIGGER TRG_INS_UPD_SISO
ON dbo.LOP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @SiSo INT, @SLHV INT, @MaLop CHAR(10), @TONGSL INT
	--lay ra ma lop tu inserted
	SELECT @MaLop = MALOP
	FROM inserted
	--lay ra si so cua lop do
	SELECT @SiSo = SISO
	FROM dbo.LOP 
	WHERE @MaLop = MALOP
	--DEM SLHV
	SELECT @SLHV = COUNT(MAHV)
	FROM dbo.HOCVIEN
	WHERE MALOP = @MaLop
	GROUP BY MALOP

	IF (@SiSo <> @SLHV)
	BEGIN
		PRINT N'Loi! So luong hoc vien phai bang si so'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT N'THEM THANH CONG'
	END
END
GO

--18--
CREATE TRIGGER TRG_INS_UPD_DK
ON dbo.DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MaMH CHAR (10), @MaMH_Truoc CHAR(10)

	SELECT @MaMH = MAMH, @MaMH_Truoc = MAMH_TRUOC
	FROM inserted

	IF EXISTS (
		SELECT *
		FROM dbo.DIEUKIEN
		WHERE (MAMH = @MaMH AND MAMH_TRUOC = @MaMH_Truoc)
			OR 
				(MAMH = @MaMH_Truoc AND MAMH_TRUOC = @MaMH)
			)
	BEGIN
		PRINT N'LOI! SAI DIEU KIEN'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT N'THANH CONG'
	END
END
GO

--19--
CREATE TRIGGER TRG_INS_UPD_GV
ON dbo.GIAOVIEN
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @HocVi CHAR(10), @HocHam CHAR(10), @HeSo NUMERIC(4,2), @ML MONEY, @MLHT MONEY

	SELECT @HocVi = HOCVI, @HocHam = HOCHAM, @HeSo = HESO, @ML = MUCLUONG
	FROM inserted
	
	SELECT @MLHT = MUCLUONG
	FROM dbo.GIAOVIEN
	WHERE HOCVI = @HocVi AND  HOCHAM = @HocHam AND HESO = @HeSo

	IF (@MLHT <> @ML)
	BEGIN
		PRINT N'LOI! GV CO CUNG HOC HAM, HOC VI, HE SO LUONG THI MUC LUONG BANG NHAU'
		ROLLBACK TRAN
	END
	ELSE 
	BEGIN
		PRINT N'THANH CONG'
	END
END
GO

--20--
CREATE TRIGGER TRG_INS_UPD_LT
ON dbo.KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MaHV CHAR(10), @LanThi INT, @DT NUMERIC(4,2), @MaMH CHAR (10)

	SELECT @MaHV = MAHV, @MaMH = MAMH, @LanThi = LANTHI 
	FROM inserted
	--Lay diem cua lan thi truoc do
	SELECT @DT = DIEM 
	FROM dbo.KETQUATHI
	WHERE MAHV = @MaHV AND MAMH = @MaMH AND LANTHI = @LanThi - 1

	IF (@LanThi > 1 AND @DT > 5)
	BEGIN 
		PRINT N'LOI! DIEM THI < 5'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT N'THANH CONG'
	END
END
GO

--21--
CREATE TRIGGER TRG_INS_UPD_NGTHI
ON dbo.KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MaHV CHAR(10), @MaMH CHAR(10), @NGTHI_TRC smalldatetime, @NGTHI_SAU smalldatetime, @LT INT

	SELECT @MaHV = MAHV, @MaMH = MAMH, @LT = LANTHI, @NGTHI_SAU = NGTHI
	FROM inserted

	SELECT @NGTHI_TRC = NGTHI
	FROM dbo.KETQUATHI
	WHERE MAHV = @MaHV AND MAMH = @MaMH AND LANTHI = @LT - 1

	IF (@NGTHI_SAU < @NGTHI_TRC)
	BEGIN
		PRINT N'LOI! NGAY THI SAU > NGAY THI TRUOC'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT N'THANH CONG'
	END
END
GO
